### PR TITLE
#174797514 Deploy base application to Heroku

### PR DESCRIPTION
**Pull request by ericus123**
**What does this PR do?**

This PR Deploy base application to Heroku.

**Description of Task to be completed?**
 
- deploy base app to heroku . 
- setup staging and production environments for the base app
- add heroku review app

**How should this be manually tested?**

- open the browser and visit base app staging environment url [https://script-heroes-bn-backend-stgng.herokuapp.com/](https://script-heroes-bn-backend-stgng.herokuapp.com/)
- open the browser and visit base app production environment  url [https://script-heroes-bn-backend.herokuapp.com/](https://script-heroes-bn-backend.herokuapp.com/)

**What are the relevant pivotal tracker stories?**

[#174797514](https://www.pivotaltracker.com/story/show/174797514)

**Screenshots (if appropriate)**

script-heroes_heroku_app_deployment

### CODE REVIEW

**Review by Habinezajanvier — COMMENTED** [review]
Hey @ericus123 , the way you documented your URL is giving us 404 error

**Review by dushimeemma — APPROVED** [review]

**Comment by BeyFaith** [comment]
Both staging & environment urls lead to an error.

**Comment by kipropbrian** [comment]
Hey Eric. Kindly create some route endpoints that can return some basic information when the url is opened on heroku. This will ensure there are no 404's or errors.

**Review by BeyFaith — COMMENTED** [review]
Both urls lead to errors

**Review by Habinezajanvier — COMMENTED** [review]
Hey @ericus123, one of your urls is giving us application error while on the other URL no route is working

**Review by Habinezajanvier — APPROVED** [review]
Great

**Review by jpirumvaa — APPROVED** [review]
Good to go

**Comment by kipropbrian** [comment]
Hey @ericus123, you have a staging and a production environment. How do you differentiate them? Are you running a final build in the production version?

**Review by kipropbrian — APPROVED** [review]

**Pull request merged**
